 import { Nunito } from 'next/font/google'
 
 import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar/Navbar'
import ClientOnly from './components/ClientOnly'
import Modal from './components/modals/Modal'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'WanderWise',
  description: 'Generated by create next app',
}


const font = Nunito({subsets:["latin"],});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>

      <ClientOnly>
        <Modal actionLabel='Submit' title='hello' isOpen/>

      <Navbar/>
      </ClientOnly>
       


        {children}</body>
    </html>
  )
}
